#!/usr/bin/env python

#
# Usage:
# AGI(/etc/asterisk/agi/mqtt,/etc/asterisk/agi/mqtt.cfg,calls/missed)
# or, to override the extension:
# AGI(/etc/asterisk/agi/mqtt,/etc/asterisk/agi/mqtt.cfg,calls/missed,+43123456789)
#

import sys
from ConfigParser import ConfigParser
import paho.mqtt.client as mqtt
import json

conffile, topic = sys.argv[1:3]

config = ConfigParser()
config.add_section('mqtt')
# set defaults for anonymous auth
config.set('mqtt', 'username', '')
config.set('mqtt', 'password', '')
config.set('mqtt', 'server', 'localhost')
config.set('mqtt', 'port', '1883')
config.read(conffile)

mqtt_server = config.get('mqtt', 'server')
mqtt_port = config.getint('mqtt', 'port')
mqtt_username = config.get('mqtt', 'username')
mqtt_password = config.get('mqtt', 'password')

agi = []
while True:
    line = sys.stdin.readline()
    if not line or line == "\n":
        break
    agi.append(line)

agi = dict([line.rstrip('\n').replace('agi_', '', 1).split(': ', 1) for line in agi])

if len(sys.argv) > 3:
    agi['extension'] = sys.argv[3]

def agi_exit(rc, args):
    if rc != 0:
        print "VERBOSE rc=%s \"%s\"" % (rc, args)
    sys.exit(rc)

def on_connect(client, userdata, flags, rc):
    if rc != 0:
        agi_exit(1, "Connection failed: %d" % rc)
    client.connected = True

client = mqtt.Client()
client.connected = False
client.username_pw_set(mqtt_username, mqtt_password)
client.on_connect = on_connect

try:
    client.connect(mqtt_server, port=mqtt_port)

except:
    agi_exit(1, "Can't connect")

while client.connected != True:
    client.loop(timeout=0.1)

infot = client.publish(topic.lower(), payload=json.dumps(agi))

if infot.rc != mqtt.MQTT_ERR_SUCCESS:
    agi_exit(1, "Can't publish message")

while infot.is_published() != True:
    client.loop(timeout=0.1)

agi_exit(0, "")
